---
kind: pipeline
name: default
type: kubernetes

steps:
- name: build_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME: ukhomeofficedigital+egar
    DOCKER_REGISTRY_URL: quay.io
    IMAGE_NAME: quay.io/ukhomeofficedigital/ddp-postgres-client
  when:
    branch:
    - main
    event:
    - push


  commands:
  # Wait for the docker service to be up
  - echo "Checking for docker availability."
  - n=0; while [ "$n" -lt 60 ] && ! docker stats --no-stream >/dev/null 2>&1; do n=$(( n + 1 )); sleep 1; done
  - echo "echo docker now available."
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_PASSWORD}" quay.io
  - docker build -t ddp-postgres-client:$${DRONE_COMMIT} .
  - docker tag ddp-postgres-client:$${DRONE_COMMIT} $${DOCKER_REGISTRY_URL}/ukhomeofficedigital/ddp-postgres-client:latest
  - docker push $${DOCKER_REGISTRY_URL}/ukhomeofficedigital/ddp-postgres-client:latest

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockersock
    temp: {}